[env:s11-gateway]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_extra_dirs = ../../../../shared
build_flags =
    -I../../../../shared
    -DCORE_DEBUG_LEVEL=3
lib_deps =
