persistence true
persistence_location /mosquitto/data/
log_dest stdout

# MQTT estándar
listener 1883
# WebSockets, para dashboards en el navegador
listener 9001
protocol websockets

# Sin autenticación: solo para desarrollo en tu LAN.
# En s10 esto se reemplaza por usuarios, ACLs y TLS en el 8883.
allow_anonymous true
